export const LOAD_CHATS_SUCCESS="LOAD_CHATS_SUCCESS";
export const LOAD_CHATS_FAILURE="LOAD_CHATS_FAILURE";
export const LOAD_MESSAGES_SUCCESS="LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_FAILURE="LOAD_MESSAGES_FAILURE";
export const MESSAGE_SENT="MESSAGE_SENT";